name: Deploy WeatherApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  build:
    runs-on: windows-2019   
    steps:
      - uses: actions/checkout@v1
      - name: setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Set env
        run: echo ::set-env name=workspace::$GITHUB_WORKSPACE
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(env) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo $npm_config_cache
        env:
          npm_config_cache: ${{ env.workspace }}/frontend_cache
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Create Build Directory
        run: mkdir _build
        
      - name: Restore NuGet packages
        run: nuget restore TheWeather.sln
        
      - name: Build the solution
        run: msbuild.exe TheWeather.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
        
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: TheWeather
          path: "./_build"
