name: Deploy WeatherApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  build:
    runs-on: windows-2019   
    steps:
      - uses: actions/checkout@v1
      - name: setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      #- name: Create Build Directory
        #run: mkdir _build
        
      - name: Restore NuGet packages
        run: nuget restore TheWeather.sln
        
      - name: Build the solution
        run: msbuild TheWeather.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
        
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: TheWeather
          path: bin\Release\publish
