name: Deploy WeatherApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PROJECT_PATH: TheWeather/TheWeather.csproj    
jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore "./myApp"
    - name: Build code
      run: dotnet build "./myApp" --configuration Release --no-restore
    - name: Test code 
      run: dotnet test "./myApp" --no-restore --verbosity normal
    - name: Publish application
      run: dotnet publish "./myApp" -c Release -o myApp
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: "./myApp" 
