name: Deploy WeatherApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  build:
    runs-on: windows-latest   
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      #- name: Navigate to Workspace
        #run: cd $GITHUB_WORKSPACE

      #- name: Create Build Directory
        #run: mkdir _build
        
      - name: Restore NuGet packages
        run: nuget restore TheWeather.sln
        
      - name: Restore
        run: dotnet restore
 
      - name: Build
        run: dotnet build --configuration Release --no-restore
 
      - name: Test
        run: dotnet test --no-restore
      #- name: Build the solution
        #run: msbuild.exe TheWeather.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
      #- name: Publish
        #run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Upload artifact
          path: ./publish
          if-no-files-found: error
     
