name: Deploy WeatherApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PROJECT_PATH: TheWeather/TheWeather.csproj    
jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '5.0.x' ]
        runtime: [ 'win-x64']

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1	
      uses: actions/setup-dotnet@v1	
      with:	
        dotnet-version: 3.1.x
    
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    #- name: Build
      #run: dotnet build --no-restore
    
    - name: Publish
      run: dotnet publish

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: TheWeather-${{ matrix.runtime }}-${{ matrix.dotnet }}
        path: ./publish
        if-no-files-found: error
