name: Deploy WeatherApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
    PROJECT_PATH: TheWeather/TheWeather.csproj
    
jobs:

  build:
    runs-on: windows-latest   
    steps:
      - uses: actions/checkout@v2
      
      - name: setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
      
      - name: Restore NuGet packages
        run: nuget restore TheWeather.sln
        
      - name: Build the solution
        run: msbuild TheWeather.sln
        
